apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-demo-app-depl
spec:
  selector:
    matchLabels:
      app: react-app-sample
  replicas: 2
  template:
    metadata:
      labels:
        app: react-app-sample
    spec:
      containers:
        - name: react-app-container
          image: bhmat89/my-react-demo-app
