apiVersion: v1
kind: Service
metadata:
  name: react-demo-app-serv
spec:
  selector:
    app: react-app-sample
  ports:
    - name: react-app-port
      port: 3000
      targetPort: 3000
  type: NodePort
